services:
    app:
        container_name: localstack-ui
        image: diegueradev/localstack-ui:latest
        ports:
            - "80:80"

    localstack:
        container_name: localstack
        image: localstack/localstack
        environment:
            - SERVICES=sns,sqs
            - DEBUG=1
