services:
  app:
    build:
      context: .
    container_name: localstack-ui
    ports:
      - "80:80"
    volumes:
      - mydb:/var/www/html/database/database.sqlite

  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1

volumes:
  mydb:
    driver: local
