services:
    app:
        container_name: localstack-ui
        build:
          context: .
          dockerfile: full.Dockerfile
        ports:
            - "80:8090"

    localstack:
        container_name: localstack
        image: localstack/localstack
        environment:
            - SERVICES=sns,sqs
            - DEBUG=1
