services:

    redis:
        container_name: redis
        image: redis:alpine
        network_mode: host

    localstack:
        container_name: localstack
        image: localstack/localstack
        network_mode: host
        environment:
            - SERVICES=sns,sqs
            - DEBUG=1
        volumes:
            - localstack-vol:/var/lib/localstack

volumes:
    localstack-vol:
        driver: local
    mysql:
        driver: local
